### ISSUE TITLE
Problem: blockchain regression fails on listed blocks with error "not yet implemented"

### ISSUE THREAD

**Issue by sjmackenzie** [ETCDEVTeam/sputnikvm#179]
Problem: 
block
46147 
46214
46217
46219
46237
46253
... (seems to be many)
fails with this error:

```
$ RUST_BACKTRACE=1 cargo run --bin regtests -- -r http://127.0.0.1:8545 -n 46147
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `/home/stewart/dev/etcdev/sputnikvm/target/debug/regtests -r 'http://127.0.0.1:8545' -n 46147`
net version: 1
block 46147, transaction count: 1

working on transaction 0x5c504ed432cb51138bcf09aa5e8a410dd4a1e204ef84bfed1be16dfba1b22060
Feeding VM account code at 0x5df9b87991262f6ba471f09758cde1c0fc1de734 ...
VM exited with ExitedOk.
thread 'main' panicked at 'not yet implemented', src/bin/main.rs:167
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   6: regtests::test_block
             at ./src/bin/main.rs:167
   7: regtests::main
             at ./src/bin/main.rs:196
   8: std::panicking::try::do_call
   9: __rust_maybe_catch_panic
  10: std::rt::lang_start
  11: main
  12: __libc_start_main
  13: _start
```

**Comment by sjmackenzie** [comment]
solved by https://github.com/ethereumproject/sputnikvm/pull/181
