### ISSUE TITLE
Problem: blockchain regression fails on listed blocks with error "assertion failed: !v"

### ISSUE THREAD

**Issue by sjmackenzie** [ETCDEVTeam/sputnikvm#180]
Problem: 
blocks
46169
46170
46194
46205
46220
46230
46235
46238
46240
46242
46245
46246
46247
46250
46251
46254
46256
46259
46260
46261
46262
46269
... (seems to be many)
fails with this error

```
working on transaction 0x19f1df2c7ee6b464720ad28e903aeda1a5ad8780afc22f0b960827bd4fcf656d
Feeding VM account code at 0x5c12a8e43faf884521c2454f39560e6c265a68c8 ...
thread 'main' panicked at 'assertion failed: !v', bigint/src/u256.rs:362
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   6: <bigint::u256::U256 as core::ops::Sub>::sub
             at /home/stewart/dev/fractalide/etcdev/sputnikvm/bigint/src/u256.rs:362
   7: sputnikvm::vm::commit::account::AccountState::decrease_balance
             at /home/stewart/dev/fractalide/etcdev/sputnikvm/sputnikvm/src/vm/commit/account.rs:383
   8: <sputnikvm::vm::eval::Machine<M>>::finalize
             at /home/stewart/dev/fractalide/etcdev/sputnikvm/sputnikvm/src/vm/eval/mod.rs:196
   9: <sputnikvm::vm::transaction::TransactionVM<M> as sputnikvm::vm::VM>::step
             at /home/stewart/dev/fractalide/etcdev/sputnikvm/sputnikvm/src/vm/transaction.rs:224
  10: sputnikvm::vm::VM::fire
             at /home/stewart/dev/fractalide/etcdev/sputnikvm/sputnikvm/src/vm/mod.rs:61
  11: regtests::handle_fire
             at ./src/bin/main.rs:67
  12: regtests::test_block
             at ./src/bin/main.rs:134
  13: regtests::main
             at ./src/bin/main.rs:192
  14: std::panicking::try::do_call
  15: __rust_maybe_catch_panic
  16: std::rt::lang_start
  17: main
  18: __libc_start_main
  19: _start
             at ../sysdeps/x86_64/start.S:120
```

**Comment by sjmackenzie** [comment]
solved by #182
