### ISSUE TITLE
Problem: blockchain regression fails on listed blocks with error "invalid type: unit value, expected struct RPCBlock"

### ISSUE THREAD

**Issue by sjmackenzie** [ETCDEVTeam/sputnikvm#183]
Problem:
blocks 
46274
46284
46343
46344
46390
46398
46456
46480
46531
46546
46582
46647
46674
46695
46710
46722
46724
46797
46823
46826
46854
46878
46891
46893
46947
46955
46985
46989
47026
47185
47214
47233
47237
47250
47254
47318
47361
47395
47403
47425
47460
47498
47571
47584
47633
47640
47657
47658
47689
47707
47719
47726
47752
47830
47913
48015
48034
48040

... (seems to be many)
fail with this error
```
block 46274, transaction count: 1

working on transaction 0x669890439f5093b7dfbca9b06de1d6da78ceacf1ec0753252b3e6cf10ff81a3e
Feeding VM account code at 0xff68c2f39c4e7fe2f92c2dc2f8615b1bf070e0fa ...
VM exited with ExitedOk.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ErrorImpl { code: Message("invalid type: unit value, expected struct RPCBlock"), line: 1, column: 39 }', /checkout/src/libcore/result.rs:859
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic
   6: std::panicking::begin_panic_fmt
   7: rust_begin_unwind
   8: core::panicking::panic_fmt
   9: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:29
  10: <core::result::Result<T, E>>::unwrap
             at /checkout/src/libcore/result.rs:737
  11: gethrpc::GethRPCClient::rpc_object_request
             at /home/stewart/dev/fractalide/etcdev/sputnikvm/gethrpc/src/lib.rs:162
  12: gethrpc::GethRPCClient::get_block_by_hash
             at /home/stewart/dev/fractalide/etcdev/sputnikvm/gethrpc/src/lib.rs:278
  13: regtests::is_miner_or_uncle
             at ./src/bin/main.rs:124
  14: regtests::test_block
             at ./src/bin/main.rs:214
  15: regtests::main
             at ./src/bin/main.rs:259
  16: std::panicking::try::do_call
  17: __rust_maybe_catch_panic
  18: std::rt::lang_start
  19: main
  20: __libc_start_main
  21: _start
             at ../sysdeps/x86_64/start.S:120

```

**Comment by sjmackenzie** [comment]
updated issue description new failing blocks.

**Comment by sorpaas** [comment]
FYI, those are all fixed in upstream. See https://jenkins.that.world/job/SputnikVM%20Blockchain%20Regression%20Ongoing/11/console

I'll create a new PR only when #175 is resolved.

**Comment by sjmackenzie** [comment]
This repository *is* upstream.

**Comment by sorpaas** [comment]
Have fun arguing about definitions and names~

**Comment by sjmackenzie** [comment]
keeping old name for the historical record.
