### ISSUE TITLE
Problem: blockchain regression fails on listed blocks with error "assertion failed: carry == 0"

### ISSUE THREAD

**Issue by sjmackenzie** [ETCDEVTeam/sputnikvm#184]
Problem:
blocks
49987
49994
200597
204007

fails with:
```
block 49987, transaction count: 1

working on transaction 0x9e2783b3c42dea792faf9b636aeba0b4384bc0ec19f1a47d931ffee686869637
Feeding VM account code at 0x109c4f2ccc82c4d77bde15f306707320294aea3f ...
Feeding VM account at 0x109c4f2ccc82c4d77bde15f306707320294aea3f ...
Feeding VM account storage at 0x109c4f2ccc82c4d77bde15f306707320294aea3f with index 0x0000000000000000000000000000000000000000000000000000000000000001 ...
Feeding VM account storage at 0x109c4f2ccc82c4d77bde15f306707320294aea3f with index 0x0000000000000000000000000000000000000000000000000000000000000003 ...
Feeding VM account storage at 0x109c4f2ccc82c4d77bde15f306707320294aea3f with index 0xc2575a0e9e593c00f959f8c92f12db2869c3395a3b0502d05e2516446f71f85c ...
Feeding VM account storage at 0x109c4f2ccc82c4d77bde15f306707320294aea3f with index 0x0000000000000000000000000000000000000000000000000000000000000000 ...
Feeding VM account storage at 0x109c4f2ccc82c4d77bde15f306707320294aea3f with index 0xc2575a0e9e593c00f959f8c92f12db2869c3395a3b0502d05e2516446f71f85b ...
Feeding VM account at 0x881b0a4e9c55d08e31d8d3c022144d75a454211c ...
thread 'main' panicked at 'assertion failed: carry == 0', bigint/src/u512.rs:143
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   6: <bigint::u512::U512 as core::ops::Add>::add
             at /home/stewart/dev/fractalide/etcdev/sputnikvm/bigint/src/u512.rs:143
   7: <sputnikvm::utils::gas::Gas as core::ops::Add>::add
             at /home/stewart/dev/fractalide/etcdev/sputnikvm/sputnikvm/src/utils/gas.rs:65
   8: <sputnikvm::vm::eval::Machine<M>>::step
             at /home/stewart/dev/fractalide/etcdev/sputnikvm/sputnikvm/src/vm/eval/mod.rs:344
   9: <sputnikvm::vm::ContextVM<M> as sputnikvm::vm::VM>::step
             at /home/stewart/dev/fractalide/etcdev/sputnikvm/sputnikvm/src/vm/mod.rs:154
  10: <sputnikvm::vm::transaction::TransactionVM<M> as sputnikvm::vm::VM>::step
             at /home/stewart/dev/fractalide/etcdev/sputnikvm/sputnikvm/src/vm/transaction.rs:213
  11: sputnikvm::vm::VM::fire
             at /home/stewart/dev/fractalide/etcdev/sputnikvm/sputnikvm/src/vm/mod.rs:61
  12: regtests::handle_fire
             at ./src/bin/main.rs:67
  13: regtests::test_block
             at ./src/bin/main.rs:154
  14: regtests::main
             at ./src/bin/main.rs:259
  15: std::panicking::try::do_call
  16: __rust_maybe_catch_panic
  17: std::rt::lang_start
  18: main
  19: __libc_start_main
  20: _start
             at ../sysdeps/x86_64/start.S:120
```

**Comment by sjmackenzie** [comment]
fixed in #196
