### ISSUE TITLE
Problem: blockchain regression fails on listed blocks with error "assertion failed: M256::from_str(&expected_value).unwrap() == value"

### ISSUE THREAD

**Issue by sjmackenzie** [ETCDEVTeam/sputnikvm#185]
Problem:
blocks
50107
50438
50559
50820

fail with this error:
```
block 50107, transaction count: 1

working on transaction 0x3f97c969ddf71f515ce5373b1f8e76e9fd7016611d8ce455881009414301789e
Feeding VM account code at 0x109c4f2ccc82c4d77bde15f306707320294aea3f ...
Feeding VM account at 0x109c4f2ccc82c4d77bde15f306707320294aea3f ...
Feeding VM account storage at 0x109c4f2ccc82c4d77bde15f306707320294aea3f with index 0x0000000000000000000000000000000000000000000000000000000000000001 ...
Feeding VM account storage at 0x109c4f2ccc82c4d77bde15f306707320294aea3f with index 0x0000000000000000000000000000000000000000000000000000000000000003 ...
Feeding VM account storage at 0x109c4f2ccc82c4d77bde15f306707320294aea3f with index 0xc2575a0e9e593c00f959f8c92f12db2869c3395a3b0502d05e2516446f71f85c ...
Feeding VM account storage at 0x109c4f2ccc82c4d77bde15f306707320294aea3f with index 0x0000000000000000000000000000000000000000000000000000000000000000 ...
Feeding VM account storage at 0x109c4f2ccc82c4d77bde15f306707320294aea3f with index 0xc2575a0e9e593c00f959f8c92f12db2869c3395a3b0502d05e2516446f71f85b ...
Feeding VM account at 0x881b0a4e9c55d08e31d8d3c022144d75a454211c ...
Feeding VM account storage at 0x109c4f2ccc82c4d77bde15f306707320294aea3f with index 0x0000000000000000000000000000000000000000000000000000000000000002 ...
VM exited with ExitedErr(EmptyGas).
thread 'main' panicked at 'assertion failed: M256::from_str(&expected_value).unwrap() == value', src/bin/main.rs:184
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   6: regtests::test_block
             at ./src/bin/main.rs:184
   7: regtests::main
             at ./src/bin/main.rs:259
   8: std::panicking::try::do_call
   9: __rust_maybe_catch_panic
  10: std::rt::lang_start
  11: main
  12: __libc_start_main
  13: _start
             at ../sysdeps/x86_64/start.S:120
```

**Comment by sjmackenzie** [comment]
fixed in #196
