### ISSUE TITLE
Problem: blockchain regression fails on listed blocks with error "assertion failed: U256::from_str(&expected_balance).unwrap() == balance"

### ISSUE THREAD

**Issue by sjmackenzie** [ETCDEVTeam/sputnikvm#187]
Problem:
blocks 
50295
50324
50588
50622
50774
50871
51014
201653

fail with this error:
```
block 50295, transaction count: 1

working on transaction 0xcd31cbd995a5363263bde279a5ca00155067db49a1dc0a32b5ddeb6519a0c887
Feeding VM account code at 0x109c4f2ccc82c4d77bde15f306707320294aea3f ...
Feeding VM account at 0x109c4f2ccc82c4d77bde15f306707320294aea3f ...
Feeding VM account storage at 0x109c4f2ccc82c4d77bde15f306707320294aea3f with index 0x0000000000000000000000000000000000000000000000000000000000000001 ...
Feeding VM account storage at 0x109c4f2ccc82c4d77bde15f306707320294aea3f with index 0x0000000000000000000000000000000000000000000000000000000000000003 ...
Feeding VM account storage at 0x109c4f2ccc82c4d77bde15f306707320294aea3f with index 0xc2575a0e9e593c00f959f8c92f12db2869c3395a3b0502d05e2516446f71f860 ...
Feeding VM account storage at 0x109c4f2ccc82c4d77bde15f306707320294aea3f with index 0x0000000000000000000000000000000000000000000000000000000000000000 ...
Feeding VM account storage at 0x109c4f2ccc82c4d77bde15f306707320294aea3f with index 0x0000000000000000000000000000000000000000000000000000000000000002 ...
Feeding VM account storage at 0x109c4f2ccc82c4d77bde15f306707320294aea3f with index 0xc2575a0e9e593c00f959f8c92f12db2869c3395a3b0502d05e2516446f71f85b ...
Feeding VM account at 0x881b0a4e9c55d08e31d8d3c022144d75a454211c ...
Feeding VM account storage at 0x109c4f2ccc82c4d77bde15f306707320294aea3f with index 0xc2575a0e9e593c00f959f8c92f12db2869c3395a3b0502d05e2516446f71f85c ...
Feeding VM account at 0xfd2605a2bf58fdbb90db1da55df61628b47f9e8c ...
Feeding VM account storage at 0x109c4f2ccc82c4d77bde15f306707320294aea3f with index 0xc2575a0e9e593c00f959f8c92f12db2869c3395a3b0502d05e2516446f71f85d ...
Feeding VM account at 0x834e9b529ac9fa63b39a06f8d8c9b0d6791fa5df ...
VM exited with ExitedOk.
thread 'main' panicked at 'assertion failed: U256::from_str(&expected_balance).unwrap() == balance', src/bin/main.rs:177
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   6: regtests::test_block
             at ./src/bin/main.rs:177
   7: regtests::main
             at ./src/bin/main.rs:259
   8: std::panicking::try::do_call
   9: __rust_maybe_catch_panic
  10: std::rt::lang_start
  11: main
  12: __libc_start_main
  13: _start
             at ../sysdeps/x86_64/start.S:120
```

**Comment by sjmackenzie** [comment]
fixed in #196
