### ISSUE TITLE
Problem: blockchain regression fails on listed blocks with error "missing field `transactions`"

### ISSUE THREAD

**Issue by sjmackenzie** [ETCDEVTeam/sputnikvm#190]
Problem:
blocks 
200138
200139
200140

with error: 
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ErrorImpl { code: Message("missing field `transactions`"), line: 1, column: 1324 }', /checkout/src/libcore/result.rs:859
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic
   6: std::panicking::begin_panic_fmt
   7: rust_begin_unwind
   8: core::panicking::panic_fmt
   9: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:29
  10: <core::result::Result<T, E>>::unwrap
             at /checkout/src/libcore/result.rs:737
  11: gethrpc::GethRPCClient::rpc_object_request
             at /home/stewart/dev/fractalide/etcdev/sputnikvm/gethrpc/src/lib.rs:163
  12: gethrpc::GethRPCClient::rpc_request
             at /home/stewart/dev/fractalide/etcdev/sputnikvm/gethrpc/src/lib.rs:144
  13: gethrpc::GethRPCClient::get_uncle_by_block_number_and_index
             at /home/stewart/dev/fractalide/etcdev/sputnikvm/gethrpc/src/lib.rs:315
  14: regtests::is_miner_or_uncle
             at ./src/bin/main.rs:124
  15: regtests::test_block
             at ./src/bin/main.rs:215
  16: regtests::main
             at ./src/bin/main.rs:260
  17: std::panicking::try::do_call
  18: __rust_maybe_catch_panic
  19: std::rt::lang_start
  20: main
  21: __libc_start_main
  22: _start
             at ../sysdeps/x86_64/start.S:120
```

**Comment by sjmackenzie** [comment]
has now become #183, now closing.
