### ISSUE TITLE
Problem: blockchain regression fails on listed blocks with error "Unhandled require: Blockhash(M256(U256([0, 0, 0, 0, 0, 0, 0, 200191]))) - not implemented yet"

### ISSUE THREAD

**Issue by sjmackenzie** [ETCDEVTeam/sputnikvm#191]
Problem:
blocks 
200194
200450
200706
200962
201218
201474
201730
201986
202242
202498
202754
203010
203266
203522
203778
204034
204290
204546
204802
205058

fail with error:
```
$ RUST_BACKTRACE=1 RUST_LOG=regtests cargo run --bin regtests -- -r http://127.0.0.1:8545 -n 200194..1000000
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `/home/stewart/dev/fractalide/etcdev/sputnikvm/target/debug/regtests -r 'http://127.0.0.1:8545' -n 200194..1000000`
net version: 1
block 200194, transaction count: 1

working on transaction 0x8fc0cba5446368f9c90ab10a0b7eddb0748602f7f89b13b32d78b10f325bee20
Feeding VM account code at 0xb278e4cb20dfbf97e78f27001f6b15288302f4d7 ...
Unhandled require: Blockhash(M256(U256([0, 0, 0, 0, 0, 0, 0, 200191])))
thread 'main' panicked at 'not yet implemented', src/bin/main.rs:109
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   6: regtests::handle_fire
             at ./src/bin/main.rs:109
   7: regtests::test_block
             at ./src/bin/main.rs:155
   8: regtests::main
             at ./src/bin/main.rs:260
   9: std::panicking::try::do_call
  10: __rust_maybe_catch_panic
  11: std::rt::lang_start
  12: main
  13: __libc_start_main
  14: _start
             at ../sysdeps/x86_64/start.S:120
```

**Comment by sorpaas** [comment]
This should be fixed already at release v0.2.
